# Collection of LED strips and/or whole matrices
leds:
  sections_y:
    - name: col_1
      sections_x:
        - name: row_1
          pin: D18
          brightness: 1           # Reduces the brightness for this section
          auto_write: false
          pixel_order: GRB 
          layout_fix: true        # true = S-Layout, false = Z-Layout, usually true due to reducing circuit length
          layout_reverse: false   # true = reverse the layout, false = keep the layout
          layout_rotate: 0        # 0 = no rotation, 1 = 90°, 2 = 180°, 3 = 270°
          section_width: 48       # width of the section, number of LEDs after rotation
          section_height: 24      # height of the section, number of LEDs after rotation


# UDP server config
udp:
  listen_ip: 0.0.0.0
  listen_port: 54321
  timeout: 30
  fps_hardlimit: 30