# Collection of LED strips and/or whole matrices
leds:
  sections_y:
    - name: col_1
      sections_x:
        - name: col1_row_1
          pin: D18
          brightness: 0.05           # Reduces the brightness for this section
          auto_write: false
          pixel_order: GRB 
          layout_fix: true        # true = S-Layout, false = Z-Layout, usually true due to reducing circuit length
          layout_reverse: false   # true = reverse the layout, false = keep the layout
          layout_rotate: 90       # 0 = no rotation, 90 = 90° clockwise, 180 = 180° clockwise, 270 = 270° clockwise
          section_width: 24       # width of the section, number of LEDs after rotation
          section_height: 48      # height of the section, number of LEDs after rotation

# UDP server config
udp:
  listen_ip: 0.0.0.0
  listen_port: 54321
  timeout: 30
  fps_hardlimit: 30